#!/bin/bash
# this file copies the compiled+fingerprinted files that can be loaded directly from a modern website

# create the folder we're exporting to npm
mkdir -p ./bundled

# copy compiled element
cp ./dist/_astro/scrollable-element.*.js ./bundled/scrollable-element.js

# copy lit directives
cp ./dist/_astro/directive-helpers.*.js ./bundled/directive-helpers.js

# change fingerprinted references like `directive-helpers.0x1337.js` to the stable name `directive-helpers.js``
sed -i '' 's/directive-helpers\..*\.js/directive-helpers.js/g' ./bundled/scrollable-element.js
